name: counter_app_with_selective_rebuild
description: Counter demo app with selective rebuild implemented with 'reduced' API and 'reduced_fluttercommand' implementation as an example of how to use the 'reduced_fluttercommand' package.
publish_to: 'none' 
version: 0.2.1+3

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  reduced: 0.2.1
  reduced_fluttercommand: 
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
